### ISSUE TITLE
Different README provided local directory and actual one

### ISSUE THREAD

**Issue by MixeroTN** [RobloxianDemo/github-label-presets#1]
**Describe the Bug**
`Packages` folder in `src` is unnecessary. The command in `README.md` under `Usage With [@Financial-Times/github-label-sync]` section contains a directory without `Packages` folder (straight from `src` to `Strict`), so it throws an error in sync command. Moving this folder's content into parent repository simplifies the project structure and makes it valid with the section mentioned.

**To Reproduce**
1. Copy `github-label-sync` command with local directory parameter from `README.md` - section `Usage With [@Financial-Times/github-label-sync]`
1. Run copied `github-label-sync` command
2. See error

**The Expected Behavior**
The actual directory should be the same as provided in `README.md`.

**Screenshots**
Not needed.

**Environment (please provide the following information):**

-   OS: Windows
-   Package Version(s): v1.1.0

**Additional Context**
-

**Comment by RobloxianDemo** [comment]
Hey! 👋 

I was intending on doing that structure in that manner for readability's sake, though I understand the concern!

Thank you for submitting your concerns, and I'll look towards resolving it for the next user! 😄
